name: Workflow CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Setting up job..."

      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version
          env | sort

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow matplotlib seaborn imblearn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f MLProject/requirements.txt ]; then pip install -r MLProject/requirements.txt; fi

      - name: Run mlflow project
        shell: bash -l {0}
        working-directory: ./MLProject
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        run: |
          # Run MLflow Project
          python modeling.py \
            --output_dir=models/model.pkl \
            --test_size=0.2 \
            --random_state=42

      - name: Get latest MLflow run_id
        working-directory: ./MLProject
        run: |
          # Contoh perintah untuk mendapatkan run_id terakhir
          echo "RUN_ID=$(mlflow runs list -v | grep -v 'Run ID' | head -1 | awk '{print $4}')" >> $GITHUB_ENV
          echo "Latest MLflow run_id: ${{ env.RUN_ID }}"

      - name: Install Python dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib


      - name: Build Docker Model
        uses: docker/build-push-action@v5
        with:
          context: ./MLProject
          push: false
          tags: ml-workflow:latest

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        if: github.event_name != 'pull_request'
        run: |
          docker tag ml-workflow:latest ${{ secrets.DOCKER_HUB_USERNAME }}/ml-workflow:latest
          docker tag ml-workflow:latest ${{ secrets.DOCKER_HUB_USERNAME }}/ml-workflow:${{ github.sha }}

      - name: Push Docker Image
        if: github.event_name != 'pull_request'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ml-workflow:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ml-workflow:${{ github.sha }}

      - name: Post Log in to Docker Hub
        run: echo "Post login to Docker Hub completed"

      - name: Post Set up Python 3.12.7
        run: echo "Post Python setup completed"

      - name: Post Run actions/checkout@v3
        run: echo "Post checkout completed"

      - name: Complete job
        run: echo "Workflow completed successfully!"